[2021-07-20 09:28:46,785] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: ticker_yahoo.extract_task 2021-07-17T07:00:00+00:00 [queued]>
[2021-07-20 09:28:46,867] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: ticker_yahoo.extract_task 2021-07-17T07:00:00+00:00 [queued]>
[2021-07-20 09:28:46,890] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 09:28:46,896] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2021-07-20 09:28:46,905] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 09:28:46,960] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): extract_task> on 2021-07-17T07:00:00+00:00
[2021-07-20 09:28:47,015] {standard_task_runner.py:52} INFO - Started process 545 to run task
[2021-07-20 09:28:47,038] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ticker_yahoo', 'extract_task', '2021-07-17T07:00:00+00:00', '--job-id', '1762', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/seleniumtest.py', '--cfg-path', '/tmp/tmpukuuaepc', '--error-file', '/tmp/tmpoq31texu']
[2021-07-20 09:28:47,041] {standard_task_runner.py:77} INFO - Job 1762: Subtask extract_task
[2021-07-20 09:28:47,240] {logging_mixin.py:104} INFO - Running <TaskInstance: ticker_yahoo.extract_task 2021-07-17T07:00:00+00:00 [running]> on host 13346afafa5b
[2021-07-20 09:28:47,400] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ticker_yahoo
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2021-07-17T07:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-17T07:00:00+00:00
[2021-07-20 09:30:13,016] {logging_mixin.py:104} INFO - comapny name: 20 Microns Limited (20MICRONS.NS)
[2021-07-20 09:30:13,017] {logging_mixin.py:104} INFO - extracted ticker: 20MICRONS.NS
[2021-07-20 09:30:54,698] {logging_mixin.py:104} INFO - comapny name: 21ST CENTURY MANAG (21STCENMGM.NS)
[2021-07-20 09:30:54,699] {logging_mixin.py:104} INFO - extracted ticker: 21STCENMGM.NS
[2021-07-20 09:31:28,846] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/seleniumtest.py", line 61, in extract
    ticker = companyname = str(companyname[0].text)
IndexError: list index out of range
[2021-07-20 09:31:29,056] {taskinstance.py:1531} INFO - Marking task as FAILED. dag_id=ticker_yahoo, task_id=extract_task, execution_date=20210717T070000, start_date=20210720T092846, end_date=20210720T093129
[2021-07-20 09:31:29,316] {local_task_job.py:151} INFO - Task exited with return code 1
