[2021-07-16 14:10:52,423] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: ticker_yahoo.extract_task 2021-07-16T14:10:39.022312+00:00 [queued]>
[2021-07-16 14:10:52,461] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: ticker_yahoo.extract_task 2021-07-16T14:10:39.022312+00:00 [queued]>
[2021-07-16 14:10:52,463] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-16 14:10:52,464] {taskinstance.py:1068} INFO - Starting attempt 1 of 2
[2021-07-16 14:10:52,465] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-16 14:10:52,509] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): extract_task> on 2021-07-16T14:10:39.022312+00:00
[2021-07-16 14:10:52,547] {standard_task_runner.py:52} INFO - Started process 1588 to run task
[2021-07-16 14:10:52,555] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ticker_yahoo', 'extract_task', '2021-07-16T14:10:39.022312+00:00', '--job-id', '739', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/seleniumtest.py', '--cfg-path', '/tmp/tmp3_gohuw9', '--error-file', '/tmp/tmpjpxxn7he']
[2021-07-16 14:10:52,559] {standard_task_runner.py:77} INFO - Job 739: Subtask extract_task
[2021-07-16 14:10:52,757] {logging_mixin.py:104} INFO - Running <TaskInstance: ticker_yahoo.extract_task 2021-07-16T14:10:39.022312+00:00 [running]> on host 5d5ba9428780
[2021-07-16 14:10:53,076] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ticker_yahoo
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2021-07-16T14:10:39.022312+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-16T14:10:39.022312+00:00
[2021-07-16 14:12:40,675] {logging_mixin.py:104} INFO - comapny name: 20 Microns Limited (20MICRONS.NS)
[2021-07-16 14:12:40,680] {logging_mixin.py:104} INFO - extracted ticker: 20MICRONS.NS
[2021-07-16 14:13:16,170] {logging_mixin.py:104} INFO - comapny name: 21ST CENTURY MANAG (21STCENMGM.NS)
[2021-07-16 14:13:16,198] {logging_mixin.py:104} INFO - extracted ticker: 21STCENMGM.NS
[2021-07-16 14:13:48,442] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/seleniumtest.py", line 61, in extract
    ticker = companyname = str(companyname[0].text)
IndexError: list index out of range
[2021-07-16 14:13:48,500] {taskinstance.py:1531} INFO - Marking task as UP_FOR_RETRY. dag_id=ticker_yahoo, task_id=extract_task, execution_date=20210716T141039, start_date=20210716T141052, end_date=20210716T141348
[2021-07-16 14:13:48,735] {local_task_job.py:151} INFO - Task exited with return code 1
